### ISSUE TITLE
train

### ISSUE THREAD

**Issue by sunsunshark** [hyn2028/tpdm#2]
I'm implementing your code.Is it convenient for you to provide your CT training and test data set files? If it is ok.This my email:308299414@qq.com.I would appreciate it

**Comment by hyn2028** [comment]
We apologize for the long wait. Checkpoints and sample volumes related to LDCT-CUBE which was used in our paper have just been released, please see the updated README. 

However, The LDCT-CUBE checkpoint originated from an experiment to observe the behavior of TPDM when the dataset was extremely small (10 volumes) to train a 3D model. Therefore, its performance may be insufficient for use in abdominal CT-related tasks.
