### ISSUE TITLE
Request for AAPM CT checkpoint in the paper.

### ISSUE THREAD

**Issue by Jenn-He** [hyn2028/tpdm#6]
Hello, your paper showcases excellent reconstruction performance of sparse view CT, which has piqued my interest. But what is provided in the code is a checkpoint for another set of simulated data, not for the AAPM CT dataset. I'm not sure if it's convenient to provide the pretrained checkpoint for AAPM CT. I also noticed that your previous work on DiffuseMBIR provided checkpoints for AAPM, and if TPDM could be provided, it would be more helpful in forming a comparison. Thank you.

**Comment by hyn2028** [comment]
We apologize for the long wait. Checkpoints and sample volumes related to LDCT-CUBE which was used in our paper have just been released, please see the updated README. 

However, The LDCT-CUBE checkpoint originated from an experiment to observe the behavior of TPDM when the dataset was extremely small (10 volumes) to train a 3D model. Therefore, its performance may be insufficient for use in abdominal CT-related tasks.
