### ISSUE TITLE
Score-SDE Dependecies

### ISSUE THREAD

**Issue by antonio2001c** [hyn2028/tpdm#7]
Hello.
Do you happen to know the exact dependencies versions of the score_sde code you used for training? There seems to be an error when installing the dependencies using the original repository.
Thanks and best regards.

**Comment by hyn2028** [comment]
Hi, @antonio2001c.

Unfortunately, we do not maintain a dependency for score-sde either.
Will there be a problem if you run score-sde's code with the dependency we provided?

**Comment by antonio2001c** [comment]
Ok thanks! 
There are some dependencies missing when using the ones provided. I have to do some alterations.
Thanks!
